### ISSUE TITLE
Sub-Category Overlap

### ISSUE THREAD

**Issue by TyranntX** [OpenNaja/ACSE#2]
Hello, I'm reporting an issue that may be being caused do to this tool. a number of modders use it as it seems there's only so much room available in the fossils tab (they use it to add dinosaurs as new species, which I am assuming is all it does as I a not a modder). But it seems that the New Sub Category that was added to make that possible overlaps with the Global operations one. I don't know if its being cause by this mod or if its something else completely but I felt like I should report this anyway. 

(Also this was on challenge mode on Sorna 93)

**Comment by harlequinzeg0** [comment]
open fossils category than go back to the global operations category
