### ISSUE TITLE
Mod Slots running out

### ISSUE THREAD

**Issue by ScrubLord9000** [OpenNaja/ACSE#3]
We've gotten to a point where there's more dino mods than mod slots, I think we need more modding slots... I recently installed Mantellisaurus, and the Tyrannotitan research option just vanished. I already researched it so I still have access to the dinosaur, but I would not be able to obtain this dinosaur in a new file due to, the research icon being gone.

**Comment by night140** [comment]
U have new species on campaign and challenge mod ? So why when i try to start campaign or challenge my game crashes ? If u could help ill be appreciated

**Comment by ilodev** [comment]
Sorry guys, current JWE1 additions/fixes is on hold, we are focused on the new titles right now.
