### ISSUE TITLE
Option that Crashes you.

### ISSUE THREAD

**Issue by EmsSquad** [OpenNaja/ACSE#4]
When ever running this mod there's a finished option that is there when you open up the research section. 

When you hover over the section it will cause the game to crash.

![image](https://user-images.githubusercontent.com/69817968/130370314-d3d1bc99-5666-4316-87d8-9c1ee14d06fc.png)

**Comment by ilodev** [comment]
I read it, but we are not going to action this one because currently JWE1 additions/fixes is on hold
