### ISSUE TITLE
Crashes when using it for JWE 2

### ISSUE THREAD

**Issue by SimbsCat** [OpenNaja/ACSE#7]
I'm sure that its acse thats crashing the game because even when I take all of my mods out and just leave acse main in ovldata my game crashes. once I take acse out it doesn't crash. for detail when I open jwe 2 it comes up with made with cobra but before the universal logo starts the game crashes

**Comment by ilodev** [comment]
Could you upload a picture of your Jurassic World 2\Win64\OvlData folder please? I need to confirm you followed the installation correctly.

**Comment by Knob363** [comment]
also having a crash when I open JWE 2

**Comment by ilodev** [comment]
We are preparing an ACSE release in Nexusmods to help you guys fix these problems. You will need to wait a little and then just download from there like every other mod.
