### ISSUE TITLE
Crashing when opening JWE 2

### ISSUE THREAD

**Issue by Knob363** [OpenNaja/ACSE#8]
Game crashes immediately when opening JWE 2

**Comment by Knob363** [comment]
![ACSE](https://user-images.githubusercontent.com/96273371/146476669-fd450185-3b9b-401d-a811-637020d18baa.PNG)

**Comment by ilodev** [comment]
We are preparing an ACSE release in Nexusmods to help you guys fix these problems. You will need to wait a little and then just download from there like every other mod.
